version: '3.8'
services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      #- MYSQL_DATABASE=quotes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  phpmyadmin:
            container_name: phpmyadmin
            image: phpmyadmin
            environment:
              - MYSQL_USER=root
              - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
              - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
              - PMA_HOST=mysql
            ports:
              - 8080:80
            depends_on:
              - db


volumes:
  db:
    driver: local